INSERT INTO questionnaire (name) VALUES ('Determining the type of personality according to Jung');

INSERT INTO question(text, questionnaire_id) VALUES 
('What do you prefer?', 1),
('What books do you prefer to read?', 1),
('What would you rather allow in your work?', 1),
('If you do something wrong, then:', 1),
('How do you connect with people?', 1),
('Do you consider yourself a touchy?', 1),
('Do you tend to laugh heartily?', 1),
('Do you consider yourself a person:', 1),
('Are you open or secretive?', 1),
('Do you like to analyze your experiences?', 1),
('When you are in society, you prefer it:', 1),
('Do you often feel dissatisfied with yourself?', 1),
('Do you like to organise something?', 1),
('Would you like to keep an intimate diary?', 1),
('Do you move quickly from decision to implementation?', 1),
('Does your mood change easily?', 1),
('Do you like to persuade others, to impose your views?', 1),
('Your movements:', 1),
('You are worried about possible trouble:', 1),
('In difficult cases, you:', 1);

INSERT INTO answer(text, question_id) VALUES
('a few close friends', 1),
('a large friendly company', 1),
('with an interesting story', 2),
('with the disclosure of the other`s experiences', 2),
('delay', 3),
('mistake', 3),
('acutely worried', 4),
('there are no acute experiences', 4),
('fast, easy', 5),
('slowly, carefully', 5),
('yes', 6),
('no', 6),
('yes', 7),
('no', 7),
('silent', 8),
('talkative', 8),
('open', 9),
('secretive', 9),
('yes', 10),
('no', 10),
('say', 11),
('listen', 11),
('yes, often', 12),
('no, rarely', 12),
('yes', 13),
('no', 13),
('yes', 14),
('no', 14),
('yes quickly', 15),
('no, not fast', 15),
('yes, easy', 16),
('no', 16),
('yes, I do', 17),
('no, I don`t', 17),
('fast', 18),
('slowly', 18),
('often', 19),
('rarely', 19),
('hurry up to ask for help', 20),
('do not ask for help', 20);

INSERT INTO role(name) VALUES('ROLE_USER'), ('ROLE_ADMIN');
